### ISSUE TITLE
Snad: Redstone Edition (snad) has failed to load correctly for Minecraft 1.20.1 forge version

### ISSUE THREAD

**Issue by raziel23x** [Leclowndu93150/Snad-Redstone-Edition#1]
Mod Version: Snad-1.20.1-Neo(Forge)-2.0.0
Forge Version: 47.2.30
Crash Log
https://pastebin.com/Jw58BeBy
Latest Log
https://pastebin.com/gvq5Pdsh

with latest update 2.0.0 for 1.20.1 crashes on loading of modpack

**Comment by Leclowndu93150** [comment]
downgrade to 1.X until i figure out the solution

**Comment by Leclowndu93150** [comment]
2.0.1 should be approved soon
